# This file contains specific services build and images for Windows Containers.
#
# MUST be used alongside "docker-compose.yml" in all windows container commands

version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  nosqldata:
    image: mongo:windowsservercore

  rabbitmq:
    image: spring2/rabbitmq

networks:
  default:
    external:
      name: nat