name: Deploy ordering-signalrhub

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - deploy
  workflow_run:
    workflows: ["ordering-signalrhub"]
    branches: [dev]
    types: [completed]

env:
  CHART: ordering-signalrhub
  NAMESPACE: eshop
  CHART_ROOT: deploy/k8s/helm

jobs:
  deploy-to-aci:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: aci-test-rg
          dns-name-label: aci-ordering-signalrhub-test
          image: ghcr.io/variableclass/ordering.signalrhub:latest
          registry-login-server: ghcr.io
          registry-username: ${{ github.repository_owner }}
          registry-password: ${{ secrets.GH_PAT_TOKEN }}
          name: aci-ordering-signalrhub-test
          location: norwayeast