name: Deploy ordering-backgroundtasks

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - deploy
  workflow_run:
    workflows: ["ordering-backgroundtasks"]
    branches: [dev]
    types: [completed]

env:
  CHART: ordering-backgroundtasks
  NAMESPACE: eshop
  CHART_ROOT: deploy/k8s/helm

jobs:
  deploy-to-aci:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: aci-test-rg
          dns-name-label: aci-test-rg${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/variableclass/ordering.backgroundtasks:latest
          registry-login-server: ghcr.io
          registry-username: ${{ github.repository_owner }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          name: aci-ordering.backgroundtasks-test
          location: 'west us'